// flow-typed signature: 7af9ff8dd59fda0bc12a6829f1b3b98b
// flow-typed version: <<STUB>>/mobx_v5.9.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx/lib/mobx.es6' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.min' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.module' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.umd' {
  declare module.exports: any;
}

declare module 'mobx/lib/mobx.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx/lib/mobx.es6.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.es6'>;
}
declare module 'mobx/lib/mobx.js' {
  declare module.exports: $Exports<'mobx/lib/mobx'>;
}
declare module 'mobx/lib/mobx.min.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.min'>;
}
declare module 'mobx/lib/mobx.module.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.module'>;
}
declare module 'mobx/lib/mobx.umd.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.umd'>;
}
declare module 'mobx/lib/mobx.umd.min.js' {
  declare module.exports: $Exports<'mobx/lib/mobx.umd.min'>;
}
