// flow-typed signature: b196ed931704b994eb66ce81c06d9dc3
// flow-typed version: <<STUB>>/ol_v5.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ol/array' {
  declare module.exports: any;
}

declare module 'ol/AssertionError' {
  declare module.exports: any;
}

declare module 'ol/asserts' {
  declare module.exports: any;
}

declare module 'ol/centerconstraint' {
  declare module.exports: any;
}

declare module 'ol/Collection' {
  declare module.exports: any;
}

declare module 'ol/CollectionEventType' {
  declare module.exports: any;
}

declare module 'ol/color' {
  declare module.exports: any;
}

declare module 'ol/colorlike' {
  declare module.exports: any;
}

declare module 'ol/control' {
  declare module.exports: any;
}

declare module 'ol/control/Attribution' {
  declare module.exports: any;
}

declare module 'ol/control/Control' {
  declare module.exports: any;
}

declare module 'ol/control/FullScreen' {
  declare module.exports: any;
}

declare module 'ol/control/MousePosition' {
  declare module.exports: any;
}

declare module 'ol/control/OverviewMap' {
  declare module.exports: any;
}

declare module 'ol/control/Rotate' {
  declare module.exports: any;
}

declare module 'ol/control/ScaleLine' {
  declare module.exports: any;
}

declare module 'ol/control/util' {
  declare module.exports: any;
}

declare module 'ol/control/Zoom' {
  declare module.exports: any;
}

declare module 'ol/control/ZoomSlider' {
  declare module.exports: any;
}

declare module 'ol/control/ZoomToExtent' {
  declare module.exports: any;
}

declare module 'ol/coordinate' {
  declare module.exports: any;
}

declare module 'ol/css' {
  declare module.exports: any;
}

declare module 'ol/Disposable' {
  declare module.exports: any;
}

declare module 'ol/dom' {
  declare module.exports: any;
}

declare module 'ol/easing' {
  declare module.exports: any;
}

declare module 'ol/events' {
  declare module.exports: any;
}

declare module 'ol/events/condition' {
  declare module.exports: any;
}

declare module 'ol/events/Event' {
  declare module.exports: {
    pixel: any;
  };
}

declare module 'ol/events/EventType' {
  declare module.exports: any;
}

declare module 'ol/events/KeyCode' {
  declare module.exports: any;
}

declare module 'ol/events/Target' {
  declare module.exports: any;
}

declare module 'ol/extent' {
  declare module.exports: any;
}

declare module 'ol/extent/Corner' {
  declare module.exports: any;
}

declare module 'ol/extent/Relationship' {
  declare module.exports: any;
}

declare module 'ol/Feature' {
  declare module.exports: any;
}

declare module 'ol/featureloader' {
  declare module.exports: any;
}

declare module 'ol/format' {
  declare module.exports: any;
}

declare module 'ol/format/EsriJSON' {
  declare module.exports: any;
}

declare module 'ol/format/Feature' {
  declare module.exports: any;
}

declare module 'ol/format/filter' {
  declare module.exports: any;
}

declare module 'ol/format/filter/And' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Bbox' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Comparison' {
  declare module.exports: any;
}

declare module 'ol/format/filter/ComparisonBinary' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Contains' {
  declare module.exports: any;
}

declare module 'ol/format/filter/During' {
  declare module.exports: any;
}

declare module 'ol/format/filter/EqualTo' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Filter' {
  declare module.exports: any;
}

declare module 'ol/format/filter/GreaterThan' {
  declare module.exports: any;
}

declare module 'ol/format/filter/GreaterThanOrEqualTo' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Intersects' {
  declare module.exports: any;
}

declare module 'ol/format/filter/IsBetween' {
  declare module.exports: any;
}

declare module 'ol/format/filter/IsLike' {
  declare module.exports: any;
}

declare module 'ol/format/filter/IsNull' {
  declare module.exports: any;
}

declare module 'ol/format/filter/LessThan' {
  declare module.exports: any;
}

declare module 'ol/format/filter/LessThanOrEqualTo' {
  declare module.exports: any;
}

declare module 'ol/format/filter/LogicalNary' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Not' {
  declare module.exports: any;
}

declare module 'ol/format/filter/NotEqualTo' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Or' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Spatial' {
  declare module.exports: any;
}

declare module 'ol/format/filter/Within' {
  declare module.exports: any;
}

declare module 'ol/format/FormatType' {
  declare module.exports: any;
}

declare module 'ol/format/GeoJSON' {
  declare module.exports: any;
}

declare module 'ol/format/GML' {
  declare module.exports: any;
}

declare module 'ol/format/GML2' {
  declare module.exports: any;
}

declare module 'ol/format/GML3' {
  declare module.exports: any;
}

declare module 'ol/format/GML32' {
  declare module.exports: any;
}

declare module 'ol/format/GMLBase' {
  declare module.exports: any;
}

declare module 'ol/format/GPX' {
  declare module.exports: any;
}

declare module 'ol/format/IGC' {
  declare module.exports: any;
}

declare module 'ol/format/JSONFeature' {
  declare module.exports: any;
}

declare module 'ol/format/KML' {
  declare module.exports: any;
}

declare module 'ol/format/MVT' {
  declare module.exports: any;
}

declare module 'ol/format/OSMXML' {
  declare module.exports: any;
}

declare module 'ol/format/OWS' {
  declare module.exports: any;
}

declare module 'ol/format/Polyline' {
  declare module.exports: any;
}

declare module 'ol/format/TextFeature' {
  declare module.exports: any;
}

declare module 'ol/format/TopoJSON' {
  declare module.exports: any;
}

declare module 'ol/format/WFS' {
  declare module.exports: any;
}

declare module 'ol/format/WKT' {
  declare module.exports: any;
}

declare module 'ol/format/WMSCapabilities' {
  declare module.exports: any;
}

declare module 'ol/format/WMSGetFeatureInfo' {
  declare module.exports: any;
}

declare module 'ol/format/WMTSCapabilities' {
  declare module.exports: any;
}

declare module 'ol/format/XLink' {
  declare module.exports: any;
}

declare module 'ol/format/XML' {
  declare module.exports: any;
}

declare module 'ol/format/XMLFeature' {
  declare module.exports: any;
}

declare module 'ol/format/xsd' {
  declare module.exports: any;
}

declare module 'ol/functions' {
  declare module.exports: any;
}

declare module 'ol/Geolocation' {
  declare module.exports: any;
}

declare module 'ol/geom' {
  declare module.exports: any;
}

declare module 'ol/geom/Circle' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/area' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/center' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/closest' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/contains' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/deflate' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/flip' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/geodesic' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/inflate' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/interiorpoint' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/interpolate' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/intersectsextent' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/length' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/orient' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/reverse' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/segments' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/simplify' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/straightchunk' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/textpath' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/topology' {
  declare module.exports: any;
}

declare module 'ol/geom/flat/transform' {
  declare module.exports: any;
}

declare module 'ol/geom/Geometry' {
  declare module.exports: any;
}

declare module 'ol/geom/GeometryCollection' {
  declare module.exports: any;
}

declare module 'ol/geom/GeometryLayout' {
  declare module.exports: any;
}

declare module 'ol/geom/GeometryType' {
  declare module.exports: any;
}

declare module 'ol/geom/LinearRing' {
  declare module.exports: any;
}

declare module 'ol/geom/LineString' {
  declare module.exports: any;
}

declare module 'ol/geom/MultiLineString' {
  declare module.exports: any;
}

declare module 'ol/geom/MultiPoint' {
  declare module.exports: any;
}

declare module 'ol/geom/MultiPolygon' {
  declare module.exports: any;
}

declare module 'ol/geom/Point' {
  declare module.exports: any;
}

declare module 'ol/geom/Polygon' {
  declare module.exports: any;
}

declare module 'ol/geom/SimpleGeometry' {
  declare module.exports: any;
}

declare module 'ol/Graticule' {
  declare module.exports: any;
}

declare module 'ol/has' {
  declare module.exports: any;
}

declare module 'ol/Image' {
  declare module.exports: any;
}

declare module 'ol/ImageBase' {
  declare module.exports: any;
}

declare module 'ol/ImageCanvas' {
  declare module.exports: any;
}

declare module 'ol/ImageState' {
  declare module.exports: any;
}

declare module 'ol/ImageTile' {
  declare module.exports: any;
}

declare module 'ol/interaction' {
  declare module.exports: any;
}

declare module 'ol/interaction/DoubleClickZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragAndDrop' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragBox' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragPan' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragRotate' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragRotateAndZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/DragZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/Draw' {
  declare module.exports: any;
}

declare module 'ol/interaction/Extent' {
  declare module.exports: any;
}

declare module 'ol/interaction/Interaction' {
  declare module.exports: any;
}

declare module 'ol/interaction/KeyboardPan' {
  declare module.exports: any;
}

declare module 'ol/interaction/KeyboardZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/Modify' {
  declare module.exports: any;
}

declare module 'ol/interaction/MouseWheelZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/PinchRotate' {
  declare module.exports: any;
}

declare module 'ol/interaction/PinchZoom' {
  declare module.exports: any;
}

declare module 'ol/interaction/Pointer' {
  declare module.exports: any;
}

declare module 'ol/interaction/Property' {
  declare module.exports: any;
}

declare module 'ol/interaction/Select' {
  declare module.exports: any;
}

declare module 'ol/interaction/Snap' {
  declare module.exports: any;
}

declare module 'ol/interaction/Translate' {
  declare module.exports: any;
}

declare module 'ol/Kinetic' {
  declare module.exports: any;
}

declare module 'ol/layer' {
  declare module.exports: any;
}

declare module 'ol/layer/Base' {
  declare module.exports: any;
}

declare module 'ol/layer/Group' {
  declare module.exports: any;
}

declare module 'ol/layer/Heatmap' {
  declare module.exports: any;
}

declare module 'ol/layer/Image' {
  declare module.exports: any;
}

declare module 'ol/layer/Layer' {
  declare module.exports: any;
}

declare module 'ol/layer/Property' {
  declare module.exports: any;
}

declare module 'ol/layer/Tile' {
  declare module.exports: any;
}

declare module 'ol/layer/TileProperty' {
  declare module.exports: any;
}

declare module 'ol/layer/Vector' {
  declare module.exports: any;
}

declare module 'ol/layer/VectorRenderType' {
  declare module.exports: any;
}

declare module 'ol/layer/VectorTile' {
  declare module.exports: any;
}

declare module 'ol/layer/VectorTileRenderType' {
  declare module.exports: any;
}

declare module 'ol/LayerType' {
  declare module.exports: any;
}

declare module 'ol/loadingstrategy' {
  declare module.exports: any;
}

declare module 'ol/Map' {
  declare module.exports: any;
}

declare module 'ol/MapBrowserEvent' {
  declare module.exports: any;
}

declare module 'ol/MapBrowserEventHandler' {
  declare module.exports: any;
}

declare module 'ol/MapBrowserEventType' {
  declare module.exports: any;
}

declare module 'ol/MapBrowserPointerEvent' {
  declare module.exports: any;
}

declare module 'ol/MapEvent' {
  declare module.exports: any;
}

declare module 'ol/MapEventType' {
  declare module.exports: any;
}

declare module 'ol/MapProperty' {
  declare module.exports: any;
}

declare module 'ol/math' {
  declare module.exports: any;
}

declare module 'ol/net' {
  declare module.exports: any;
}

declare module 'ol/obj' {
  declare module.exports: any;
}

declare module 'ol/Object' {
  declare module.exports: any;
}

declare module 'ol/ObjectEventType' {
  declare module.exports: any;
}

declare module 'ol/Observable' {
  declare module.exports: any;
}

declare module 'ol/Overlay' {
  declare module.exports: any;
}

declare module 'ol/OverlayPositioning' {
  declare module.exports: any;
}

declare module 'ol/pixel' {
  declare module.exports: any;
}

declare module 'ol/PluggableMap' {
  declare module.exports: any;
}

declare module 'ol/pointer/EventSource' {
  declare module.exports: any;
}

declare module 'ol/pointer/EventType' {
  declare module.exports: any;
}

declare module 'ol/pointer/MouseSource' {
  declare module.exports: any;
}

declare module 'ol/pointer/MsSource' {
  declare module.exports: any;
}

declare module 'ol/pointer/NativeSource' {
  declare module.exports: any;
}

declare module 'ol/pointer/PointerEvent' {
  declare module.exports: any;
}

declare module 'ol/pointer/PointerEventHandler' {
  declare module.exports: any;
}

declare module 'ol/pointer/TouchSource' {
  declare module.exports: any;
}

declare module 'ol/proj' {
  declare module.exports: any;
}

declare module 'ol/proj/epsg3857' {
  declare module.exports: any;
}

declare module 'ol/proj/epsg4326' {
  declare module.exports: any;
}

declare module 'ol/proj/proj4' {
  declare module.exports: any;
}

declare module 'ol/proj/Projection' {
  declare module.exports: any;
}

declare module 'ol/proj/projections' {
  declare module.exports: any;
}

declare module 'ol/proj/transforms' {
  declare module.exports: any;
}

declare module 'ol/proj/Units' {
  declare module.exports: any;
}

declare module 'ol/render' {
  declare module.exports: any;
}

declare module 'ol/render/Box' {
  declare module.exports: any;
}

declare module 'ol/render/canvas' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/ImageReplay' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/Immediate' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/Instruction' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/LineStringReplay' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/PolygonReplay' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/Replay' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/ReplayGroup' {
  declare module.exports: any;
}

declare module 'ol/render/canvas/TextReplay' {
  declare module.exports: any;
}

declare module 'ol/render/Event' {
  declare module.exports: any;
}

declare module 'ol/render/EventType' {
  declare module.exports: any;
}

declare module 'ol/render/Feature' {
  declare module.exports: any;
}

declare module 'ol/render/replay' {
  declare module.exports: any;
}

declare module 'ol/render/ReplayGroup' {
  declare module.exports: any;
}

declare module 'ol/render/ReplayType' {
  declare module.exports: any;
}

declare module 'ol/render/VectorContext' {
  declare module.exports: any;
}

declare module 'ol/render/webgl' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/CircleReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/circlereplay/defaultshader' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/circlereplay/defaultshader/Locations' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/ImageReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/Immediate' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/LineStringReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/linestringreplay/defaultshader' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/linestringreplay/defaultshader/Locations' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/PolygonReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/polygonreplay/defaultshader' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/polygonreplay/defaultshader/Locations' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/Replay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/ReplayGroup' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/TextReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/TextureReplay' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/texturereplay/defaultshader' {
  declare module.exports: any;
}

declare module 'ol/render/webgl/texturereplay/defaultshader/Locations' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/ImageLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/IntermediateCanvas' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/Layer' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/Map' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/TileLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/VectorLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/canvas/VectorTileLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/Layer' {
  declare module.exports: any;
}

declare module 'ol/renderer/Map' {
  declare module.exports: any;
}

declare module 'ol/renderer/vector' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/defaultmapshader' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/defaultmapshader/Locations' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/ImageLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/Layer' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/Map' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/TileLayer' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/tilelayershader' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/tilelayershader/Locations' {
  declare module.exports: any;
}

declare module 'ol/renderer/webgl/VectorLayer' {
  declare module.exports: any;
}

declare module 'ol/reproj' {
  declare module.exports: any;
}

declare module 'ol/reproj/common' {
  declare module.exports: any;
}

declare module 'ol/reproj/Image' {
  declare module.exports: any;
}

declare module 'ol/reproj/Tile' {
  declare module.exports: any;
}

declare module 'ol/reproj/Triangulation' {
  declare module.exports: any;
}

declare module 'ol/resolutionconstraint' {
  declare module.exports: any;
}

declare module 'ol/rotationconstraint' {
  declare module.exports: any;
}

declare module 'ol/size' {
  declare module.exports: any;
}

declare module 'ol/source' {
  declare module.exports: any;
}

declare module 'ol/source/BingMaps' {
  declare module.exports: any;
}

declare module 'ol/source/CartoDB' {
  declare module.exports: any;
}

declare module 'ol/source/Cluster' {
  declare module.exports: any;
}

declare module 'ol/source/common' {
  declare module.exports: any;
}

declare module 'ol/source/Image' {
  declare module.exports: any;
}

declare module 'ol/source/ImageArcGISRest' {
  declare module.exports: any;
}

declare module 'ol/source/ImageCanvas' {
  declare module.exports: any;
}

declare module 'ol/source/ImageMapGuide' {
  declare module.exports: any;
}

declare module 'ol/source/ImageStatic' {
  declare module.exports: any;
}

declare module 'ol/source/ImageWMS' {
  declare module.exports: any;
}

declare module 'ol/source/OSM' {
  declare module.exports: any;
}

declare module 'ol/source/Raster' {
  declare module.exports: any;
}

declare module 'ol/source/Source' {
  declare module.exports: any;
}

declare module 'ol/source/Stamen' {
  declare module.exports: any;
}

declare module 'ol/source/State' {
  declare module.exports: any;
}

declare module 'ol/source/Tile' {
  declare module.exports: any;
}

declare module 'ol/source/TileArcGISRest' {
  declare module.exports: any;
}

declare module 'ol/source/TileDebug' {
  declare module.exports: any;
}

declare module 'ol/source/TileEventType' {
  declare module.exports: any;
}

declare module 'ol/source/TileImage' {
  declare module.exports: any;
}

declare module 'ol/source/TileJSON' {
  declare module.exports: any;
}

declare module 'ol/source/TileWMS' {
  declare module.exports: any;
}

declare module 'ol/source/UrlTile' {
  declare module.exports: any;
}

declare module 'ol/source/UTFGrid' {
  declare module.exports: any;
}

declare module 'ol/source/Vector' {
  declare module.exports: any;
}

declare module 'ol/source/VectorEventType' {
  declare module.exports: any;
}

declare module 'ol/source/VectorTile' {
  declare module.exports: any;
}

declare module 'ol/source/WMSServerType' {
  declare module.exports: any;
}

declare module 'ol/source/WMTS' {
  declare module.exports: any;
}

declare module 'ol/source/WMTSRequestEncoding' {
  declare module.exports: any;
}

declare module 'ol/source/XYZ' {
  declare module.exports: any;
}

declare module 'ol/source/Zoomify' {
  declare module.exports: any;
}

declare module 'ol/sphere' {
  declare module.exports: any;
}

declare module 'ol/string' {
  declare module.exports: any;
}

declare module 'ol/structs/LinkedList' {
  declare module.exports: any;
}

declare module 'ol/structs/LRUCache' {
  declare module.exports: any;
}

declare module 'ol/structs/PriorityQueue' {
  declare module.exports: any;
}

declare module 'ol/structs/RBush' {
  declare module.exports: any;
}

declare module 'ol/style' {
  declare module.exports: any;
}

declare module 'ol/style/Atlas' {
  declare module.exports: any;
}

declare module 'ol/style/AtlasManager' {
  declare module.exports: any;
}

declare module 'ol/style/Circle' {
  declare module.exports: any;
}

declare module 'ol/style/Fill' {
  declare module.exports: any;
}

declare module 'ol/style/Icon' {
  declare module.exports: any;
}

declare module 'ol/style/IconAnchorUnits' {
  declare module.exports: any;
}

declare module 'ol/style/IconImage' {
  declare module.exports: any;
}

declare module 'ol/style/IconImageCache' {
  declare module.exports: any;
}

declare module 'ol/style/IconOrigin' {
  declare module.exports: any;
}

declare module 'ol/style/Image' {
  declare module.exports: any;
}

declare module 'ol/style/RegularShape' {
  declare module.exports: any;
}

declare module 'ol/style/Stroke' {
  declare module.exports: any;
}

declare module 'ol/style/Style' {
  declare module.exports: any;
}

declare module 'ol/style/Text' {
  declare module.exports: any;
}

declare module 'ol/style/TextPlacement' {
  declare module.exports: any;
}

declare module 'ol/Tile' {
  declare module.exports: any;
}

declare module 'ol/TileCache' {
  declare module.exports: any;
}

declare module 'ol/tilecoord' {
  declare module.exports: any;
}

declare module 'ol/tilegrid' {
  declare module.exports: any;
}

declare module 'ol/tilegrid/common' {
  declare module.exports: any;
}

declare module 'ol/tilegrid/TileGrid' {
  declare module.exports: any;
}

declare module 'ol/tilegrid/WMTS' {
  declare module.exports: any;
}

declare module 'ol/TileQueue' {
  declare module.exports: any;
}

declare module 'ol/TileRange' {
  declare module.exports: any;
}

declare module 'ol/TileState' {
  declare module.exports: any;
}

declare module 'ol/tileurlfunction' {
  declare module.exports: any;
}

declare module 'ol/transform' {
  declare module.exports: any;
}

declare module 'ol/uri' {
  declare module.exports: any;
}

declare module 'ol/util' {
  declare module.exports: any;
}

declare module 'ol/vec/mat4' {
  declare module.exports: any;
}

declare module 'ol/VectorImageTile' {
  declare module.exports: any;
}

declare module 'ol/VectorTile' {
  declare module.exports: any;
}

declare module 'ol/View' {
  declare module.exports: any;
}

declare module 'ol/ViewHint' {
  declare module.exports: any;
}

declare module 'ol/ViewProperty' {
  declare module.exports: any;
}

declare module 'ol/webgl' {
  declare module.exports: any;
}

declare module 'ol/webgl/Buffer' {
  declare module.exports: any;
}

declare module 'ol/webgl/Context' {
  declare module.exports: any;
}

declare module 'ol/webgl/ContextEventType' {
  declare module.exports: any;
}

declare module 'ol/webgl/Fragment' {
  declare module.exports: any;
}

declare module 'ol/webgl/Shader' {
  declare module.exports: any;
}

declare module 'ol/webgl/Vertex' {
  declare module.exports: any;
}

declare module 'ol/WebGLMap' {
  declare module.exports: any;
}

declare module 'ol/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ol/array.js' {
  declare module.exports: $Exports<'ol/array'>;
}
declare module 'ol/AssertionError.js' {
  declare module.exports: $Exports<'ol/AssertionError'>;
}
declare module 'ol/asserts.js' {
  declare module.exports: $Exports<'ol/asserts'>;
}
declare module 'ol/centerconstraint.js' {
  declare module.exports: $Exports<'ol/centerconstraint'>;
}
declare module 'ol/Collection.js' {
  declare module.exports: $Exports<'ol/Collection'>;
}
declare module 'ol/CollectionEventType.js' {
  declare module.exports: $Exports<'ol/CollectionEventType'>;
}
declare module 'ol/color.js' {
  declare module.exports: $Exports<'ol/color'>;
}
declare module 'ol/colorlike.js' {
  declare module.exports: $Exports<'ol/colorlike'>;
}
declare module 'ol/control.js' {
  declare module.exports: $Exports<'ol/control'>;
}
declare module 'ol/control/Attribution.js' {
  declare module.exports: $Exports<'ol/control/Attribution'>;
}
declare module 'ol/control/Control.js' {
  declare module.exports: $Exports<'ol/control/Control'>;
}
declare module 'ol/control/FullScreen.js' {
  declare module.exports: $Exports<'ol/control/FullScreen'>;
}
declare module 'ol/control/MousePosition.js' {
  declare module.exports: $Exports<'ol/control/MousePosition'>;
}
declare module 'ol/control/OverviewMap.js' {
  declare module.exports: $Exports<'ol/control/OverviewMap'>;
}
declare module 'ol/control/Rotate.js' {
  declare module.exports: $Exports<'ol/control/Rotate'>;
}
declare module 'ol/control/ScaleLine.js' {
  declare module.exports: $Exports<'ol/control/ScaleLine'>;
}
declare module 'ol/control/util.js' {
  declare module.exports: $Exports<'ol/control/util'>;
}
declare module 'ol/control/Zoom.js' {
  declare module.exports: $Exports<'ol/control/Zoom'>;
}
declare module 'ol/control/ZoomSlider.js' {
  declare module.exports: $Exports<'ol/control/ZoomSlider'>;
}
declare module 'ol/control/ZoomToExtent.js' {
  declare module.exports: $Exports<'ol/control/ZoomToExtent'>;
}
declare module 'ol/coordinate.js' {
  declare module.exports: $Exports<'ol/coordinate'>;
}
declare module 'ol/css.js' {
  declare module.exports: $Exports<'ol/css'>;
}
declare module 'ol/Disposable.js' {
  declare module.exports: $Exports<'ol/Disposable'>;
}
declare module 'ol/dom.js' {
  declare module.exports: $Exports<'ol/dom'>;
}
declare module 'ol/easing.js' {
  declare module.exports: $Exports<'ol/easing'>;
}
declare module 'ol/events.js' {
  declare module.exports: $Exports<'ol/events'>;
}
declare module 'ol/events/condition.js' {
  declare module.exports: $Exports<'ol/events/condition'>;
}
declare module 'ol/events/Event.js' {
  declare module.exports: $Exports<'ol/events/Event'>;
}
declare module 'ol/events/EventType.js' {
  declare module.exports: $Exports<'ol/events/EventType'>;
}
declare module 'ol/events/KeyCode.js' {
  declare module.exports: $Exports<'ol/events/KeyCode'>;
}
declare module 'ol/events/Target.js' {
  declare module.exports: $Exports<'ol/events/Target'>;
}
declare module 'ol/extent.js' {
  declare module.exports: $Exports<'ol/extent'>;
}
declare module 'ol/extent/Corner.js' {
  declare module.exports: $Exports<'ol/extent/Corner'>;
}
declare module 'ol/extent/Relationship.js' {
  declare module.exports: $Exports<'ol/extent/Relationship'>;
}
declare module 'ol/Feature.js' {
  declare module.exports: $Exports<'ol/Feature'>;
}
declare module 'ol/featureloader.js' {
  declare module.exports: $Exports<'ol/featureloader'>;
}
declare module 'ol/format.js' {
  declare module.exports: $Exports<'ol/format'>;
}
declare module 'ol/format/EsriJSON.js' {
  declare module.exports: $Exports<'ol/format/EsriJSON'>;
}
declare module 'ol/format/Feature.js' {
  declare module.exports: $Exports<'ol/format/Feature'>;
}
declare module 'ol/format/filter.js' {
  declare module.exports: $Exports<'ol/format/filter'>;
}
declare module 'ol/format/filter/And.js' {
  declare module.exports: $Exports<'ol/format/filter/And'>;
}
declare module 'ol/format/filter/Bbox.js' {
  declare module.exports: $Exports<'ol/format/filter/Bbox'>;
}
declare module 'ol/format/filter/Comparison.js' {
  declare module.exports: $Exports<'ol/format/filter/Comparison'>;
}
declare module 'ol/format/filter/ComparisonBinary.js' {
  declare module.exports: $Exports<'ol/format/filter/ComparisonBinary'>;
}
declare module 'ol/format/filter/Contains.js' {
  declare module.exports: $Exports<'ol/format/filter/Contains'>;
}
declare module 'ol/format/filter/During.js' {
  declare module.exports: $Exports<'ol/format/filter/During'>;
}
declare module 'ol/format/filter/EqualTo.js' {
  declare module.exports: $Exports<'ol/format/filter/EqualTo'>;
}
declare module 'ol/format/filter/Filter.js' {
  declare module.exports: $Exports<'ol/format/filter/Filter'>;
}
declare module 'ol/format/filter/GreaterThan.js' {
  declare module.exports: $Exports<'ol/format/filter/GreaterThan'>;
}
declare module 'ol/format/filter/GreaterThanOrEqualTo.js' {
  declare module.exports: $Exports<'ol/format/filter/GreaterThanOrEqualTo'>;
}
declare module 'ol/format/filter/Intersects.js' {
  declare module.exports: $Exports<'ol/format/filter/Intersects'>;
}
declare module 'ol/format/filter/IsBetween.js' {
  declare module.exports: $Exports<'ol/format/filter/IsBetween'>;
}
declare module 'ol/format/filter/IsLike.js' {
  declare module.exports: $Exports<'ol/format/filter/IsLike'>;
}
declare module 'ol/format/filter/IsNull.js' {
  declare module.exports: $Exports<'ol/format/filter/IsNull'>;
}
declare module 'ol/format/filter/LessThan.js' {
  declare module.exports: $Exports<'ol/format/filter/LessThan'>;
}
declare module 'ol/format/filter/LessThanOrEqualTo.js' {
  declare module.exports: $Exports<'ol/format/filter/LessThanOrEqualTo'>;
}
declare module 'ol/format/filter/LogicalNary.js' {
  declare module.exports: $Exports<'ol/format/filter/LogicalNary'>;
}
declare module 'ol/format/filter/Not.js' {
  declare module.exports: $Exports<'ol/format/filter/Not'>;
}
declare module 'ol/format/filter/NotEqualTo.js' {
  declare module.exports: $Exports<'ol/format/filter/NotEqualTo'>;
}
declare module 'ol/format/filter/Or.js' {
  declare module.exports: $Exports<'ol/format/filter/Or'>;
}
declare module 'ol/format/filter/Spatial.js' {
  declare module.exports: $Exports<'ol/format/filter/Spatial'>;
}
declare module 'ol/format/filter/Within.js' {
  declare module.exports: $Exports<'ol/format/filter/Within'>;
}
declare module 'ol/format/FormatType.js' {
  declare module.exports: $Exports<'ol/format/FormatType'>;
}
declare module 'ol/format/GeoJSON.js' {
  declare module.exports: $Exports<'ol/format/GeoJSON'>;
}
declare module 'ol/format/GML.js' {
  declare module.exports: $Exports<'ol/format/GML'>;
}
declare module 'ol/format/GML2.js' {
  declare module.exports: $Exports<'ol/format/GML2'>;
}
declare module 'ol/format/GML3.js' {
  declare module.exports: $Exports<'ol/format/GML3'>;
}
declare module 'ol/format/GML32.js' {
  declare module.exports: $Exports<'ol/format/GML32'>;
}
declare module 'ol/format/GMLBase.js' {
  declare module.exports: $Exports<'ol/format/GMLBase'>;
}
declare module 'ol/format/GPX.js' {
  declare module.exports: $Exports<'ol/format/GPX'>;
}
declare module 'ol/format/IGC.js' {
  declare module.exports: $Exports<'ol/format/IGC'>;
}
declare module 'ol/format/JSONFeature.js' {
  declare module.exports: $Exports<'ol/format/JSONFeature'>;
}
declare module 'ol/format/KML.js' {
  declare module.exports: $Exports<'ol/format/KML'>;
}
declare module 'ol/format/MVT.js' {
  declare module.exports: $Exports<'ol/format/MVT'>;
}
declare module 'ol/format/OSMXML.js' {
  declare module.exports: $Exports<'ol/format/OSMXML'>;
}
declare module 'ol/format/OWS.js' {
  declare module.exports: $Exports<'ol/format/OWS'>;
}
declare module 'ol/format/Polyline.js' {
  declare module.exports: $Exports<'ol/format/Polyline'>;
}
declare module 'ol/format/TextFeature.js' {
  declare module.exports: $Exports<'ol/format/TextFeature'>;
}
declare module 'ol/format/TopoJSON.js' {
  declare module.exports: $Exports<'ol/format/TopoJSON'>;
}
declare module 'ol/format/WFS.js' {
  declare module.exports: $Exports<'ol/format/WFS'>;
}
declare module 'ol/format/WKT.js' {
  declare module.exports: $Exports<'ol/format/WKT'>;
}
declare module 'ol/format/WMSCapabilities.js' {
  declare module.exports: $Exports<'ol/format/WMSCapabilities'>;
}
declare module 'ol/format/WMSGetFeatureInfo.js' {
  declare module.exports: $Exports<'ol/format/WMSGetFeatureInfo'>;
}
declare module 'ol/format/WMTSCapabilities.js' {
  declare module.exports: $Exports<'ol/format/WMTSCapabilities'>;
}
declare module 'ol/format/XLink.js' {
  declare module.exports: $Exports<'ol/format/XLink'>;
}
declare module 'ol/format/XML.js' {
  declare module.exports: $Exports<'ol/format/XML'>;
}
declare module 'ol/format/XMLFeature.js' {
  declare module.exports: $Exports<'ol/format/XMLFeature'>;
}
declare module 'ol/format/xsd.js' {
  declare module.exports: $Exports<'ol/format/xsd'>;
}
declare module 'ol/functions.js' {
  declare module.exports: $Exports<'ol/functions'>;
}
declare module 'ol/Geolocation.js' {
  declare module.exports: $Exports<'ol/Geolocation'>;
}
declare module 'ol/geom.js' {
  declare module.exports: $Exports<'ol/geom'>;
}
declare module 'ol/geom/Circle.js' {
  declare module.exports: $Exports<'ol/geom/Circle'>;
}
declare module 'ol/geom/flat/area.js' {
  declare module.exports: $Exports<'ol/geom/flat/area'>;
}
declare module 'ol/geom/flat/center.js' {
  declare module.exports: $Exports<'ol/geom/flat/center'>;
}
declare module 'ol/geom/flat/closest.js' {
  declare module.exports: $Exports<'ol/geom/flat/closest'>;
}
declare module 'ol/geom/flat/contains.js' {
  declare module.exports: $Exports<'ol/geom/flat/contains'>;
}
declare module 'ol/geom/flat/deflate.js' {
  declare module.exports: $Exports<'ol/geom/flat/deflate'>;
}
declare module 'ol/geom/flat/flip.js' {
  declare module.exports: $Exports<'ol/geom/flat/flip'>;
}
declare module 'ol/geom/flat/geodesic.js' {
  declare module.exports: $Exports<'ol/geom/flat/geodesic'>;
}
declare module 'ol/geom/flat/inflate.js' {
  declare module.exports: $Exports<'ol/geom/flat/inflate'>;
}
declare module 'ol/geom/flat/interiorpoint.js' {
  declare module.exports: $Exports<'ol/geom/flat/interiorpoint'>;
}
declare module 'ol/geom/flat/interpolate.js' {
  declare module.exports: $Exports<'ol/geom/flat/interpolate'>;
}
declare module 'ol/geom/flat/intersectsextent.js' {
  declare module.exports: $Exports<'ol/geom/flat/intersectsextent'>;
}
declare module 'ol/geom/flat/length.js' {
  declare module.exports: $Exports<'ol/geom/flat/length'>;
}
declare module 'ol/geom/flat/orient.js' {
  declare module.exports: $Exports<'ol/geom/flat/orient'>;
}
declare module 'ol/geom/flat/reverse.js' {
  declare module.exports: $Exports<'ol/geom/flat/reverse'>;
}
declare module 'ol/geom/flat/segments.js' {
  declare module.exports: $Exports<'ol/geom/flat/segments'>;
}
declare module 'ol/geom/flat/simplify.js' {
  declare module.exports: $Exports<'ol/geom/flat/simplify'>;
}
declare module 'ol/geom/flat/straightchunk.js' {
  declare module.exports: $Exports<'ol/geom/flat/straightchunk'>;
}
declare module 'ol/geom/flat/textpath.js' {
  declare module.exports: $Exports<'ol/geom/flat/textpath'>;
}
declare module 'ol/geom/flat/topology.js' {
  declare module.exports: $Exports<'ol/geom/flat/topology'>;
}
declare module 'ol/geom/flat/transform.js' {
  declare module.exports: $Exports<'ol/geom/flat/transform'>;
}
declare module 'ol/geom/Geometry.js' {
  declare module.exports: $Exports<'ol/geom/Geometry'>;
}
declare module 'ol/geom/GeometryCollection.js' {
  declare module.exports: $Exports<'ol/geom/GeometryCollection'>;
}
declare module 'ol/geom/GeometryLayout.js' {
  declare module.exports: $Exports<'ol/geom/GeometryLayout'>;
}
declare module 'ol/geom/GeometryType.js' {
  declare module.exports: $Exports<'ol/geom/GeometryType'>;
}
declare module 'ol/geom/LinearRing.js' {
  declare module.exports: $Exports<'ol/geom/LinearRing'>;
}
declare module 'ol/geom/LineString.js' {
  declare module.exports: $Exports<'ol/geom/LineString'>;
}
declare module 'ol/geom/MultiLineString.js' {
  declare module.exports: $Exports<'ol/geom/MultiLineString'>;
}
declare module 'ol/geom/MultiPoint.js' {
  declare module.exports: $Exports<'ol/geom/MultiPoint'>;
}
declare module 'ol/geom/MultiPolygon.js' {
  declare module.exports: $Exports<'ol/geom/MultiPolygon'>;
}
declare module 'ol/geom/Point.js' {
  declare module.exports: $Exports<'ol/geom/Point'>;
}
declare module 'ol/geom/Polygon.js' {
  declare module.exports: $Exports<'ol/geom/Polygon'>;
}
declare module 'ol/geom/SimpleGeometry.js' {
  declare module.exports: $Exports<'ol/geom/SimpleGeometry'>;
}
declare module 'ol/Graticule.js' {
  declare module.exports: $Exports<'ol/Graticule'>;
}
declare module 'ol/has.js' {
  declare module.exports: $Exports<'ol/has'>;
}
declare module 'ol/Image.js' {
  declare module.exports: $Exports<'ol/Image'>;
}
declare module 'ol/ImageBase.js' {
  declare module.exports: $Exports<'ol/ImageBase'>;
}
declare module 'ol/ImageCanvas.js' {
  declare module.exports: $Exports<'ol/ImageCanvas'>;
}
declare module 'ol/ImageState.js' {
  declare module.exports: $Exports<'ol/ImageState'>;
}
declare module 'ol/ImageTile.js' {
  declare module.exports: $Exports<'ol/ImageTile'>;
}
declare module 'ol/index' {
  declare module.exports: $Exports<'ol'>;
}
declare module 'ol/index.js' {
  declare module.exports: $Exports<'ol'>;
}
declare module 'ol/interaction.js' {
  declare module.exports: $Exports<'ol/interaction'>;
}
declare module 'ol/interaction/DoubleClickZoom.js' {
  declare module.exports: $Exports<'ol/interaction/DoubleClickZoom'>;
}
declare module 'ol/interaction/DragAndDrop.js' {
  declare module.exports: $Exports<'ol/interaction/DragAndDrop'>;
}
declare module 'ol/interaction/DragBox.js' {
  declare module.exports: $Exports<'ol/interaction/DragBox'>;
}
declare module 'ol/interaction/DragPan.js' {
  declare module.exports: $Exports<'ol/interaction/DragPan'>;
}
declare module 'ol/interaction/DragRotate.js' {
  declare module.exports: $Exports<'ol/interaction/DragRotate'>;
}
declare module 'ol/interaction/DragRotateAndZoom.js' {
  declare module.exports: $Exports<'ol/interaction/DragRotateAndZoom'>;
}
declare module 'ol/interaction/DragZoom.js' {
  declare module.exports: $Exports<'ol/interaction/DragZoom'>;
}
declare module 'ol/interaction/Draw.js' {
  declare module.exports: $Exports<'ol/interaction/Draw'>;
}
declare module 'ol/interaction/Extent.js' {
  declare module.exports: $Exports<'ol/interaction/Extent'>;
}
declare module 'ol/interaction/Interaction.js' {
  declare module.exports: $Exports<'ol/interaction/Interaction'>;
}
declare module 'ol/interaction/KeyboardPan.js' {
  declare module.exports: $Exports<'ol/interaction/KeyboardPan'>;
}
declare module 'ol/interaction/KeyboardZoom.js' {
  declare module.exports: $Exports<'ol/interaction/KeyboardZoom'>;
}
declare module 'ol/interaction/Modify.js' {
  declare module.exports: $Exports<'ol/interaction/Modify'>;
}
declare module 'ol/interaction/MouseWheelZoom.js' {
  declare module.exports: $Exports<'ol/interaction/MouseWheelZoom'>;
}
declare module 'ol/interaction/PinchRotate.js' {
  declare module.exports: $Exports<'ol/interaction/PinchRotate'>;
}
declare module 'ol/interaction/PinchZoom.js' {
  declare module.exports: $Exports<'ol/interaction/PinchZoom'>;
}
declare module 'ol/interaction/Pointer.js' {
  declare module.exports: $Exports<'ol/interaction/Pointer'>;
}
declare module 'ol/interaction/Property.js' {
  declare module.exports: $Exports<'ol/interaction/Property'>;
}
declare module 'ol/interaction/Select.js' {
  declare module.exports: $Exports<'ol/interaction/Select'>;
}
declare module 'ol/interaction/Snap.js' {
  declare module.exports: $Exports<'ol/interaction/Snap'>;
}
declare module 'ol/interaction/Translate.js' {
  declare module.exports: $Exports<'ol/interaction/Translate'>;
}
declare module 'ol/Kinetic.js' {
  declare module.exports: $Exports<'ol/Kinetic'>;
}
declare module 'ol/layer.js' {
  declare module.exports: $Exports<'ol/layer'>;
}
declare module 'ol/layer/Base.js' {
  declare module.exports: $Exports<'ol/layer/Base'>;
}
declare module 'ol/layer/Group.js' {
  declare module.exports: $Exports<'ol/layer/Group'>;
}
declare module 'ol/layer/Heatmap.js' {
  declare module.exports: $Exports<'ol/layer/Heatmap'>;
}
declare module 'ol/layer/Image.js' {
  declare module.exports: $Exports<'ol/layer/Image'>;
}
declare module 'ol/layer/Layer.js' {
  declare module.exports: $Exports<'ol/layer/Layer'>;
}
declare module 'ol/layer/Property.js' {
  declare module.exports: $Exports<'ol/layer/Property'>;
}
declare module 'ol/layer/Tile.js' {
  declare module.exports: $Exports<'ol/layer/Tile'>;
}
declare module 'ol/layer/TileProperty.js' {
  declare module.exports: $Exports<'ol/layer/TileProperty'>;
}
declare module 'ol/layer/Vector.js' {
  declare module.exports: $Exports<'ol/layer/Vector'>;
}
declare module 'ol/layer/VectorRenderType.js' {
  declare module.exports: $Exports<'ol/layer/VectorRenderType'>;
}
declare module 'ol/layer/VectorTile.js' {
  declare module.exports: $Exports<'ol/layer/VectorTile'>;
}
declare module 'ol/layer/VectorTileRenderType.js' {
  declare module.exports: $Exports<'ol/layer/VectorTileRenderType'>;
}
declare module 'ol/LayerType.js' {
  declare module.exports: $Exports<'ol/LayerType'>;
}
declare module 'ol/loadingstrategy.js' {
  declare module.exports: $Exports<'ol/loadingstrategy'>;
}
declare module 'ol/Map.js' {
  declare module.exports: $Exports<'ol/Map'>;
}
declare module 'ol/MapBrowserEvent.js' {
  declare module.exports: $Exports<'ol/MapBrowserEvent'>;
}
declare module 'ol/MapBrowserEventHandler.js' {
  declare module.exports: $Exports<'ol/MapBrowserEventHandler'>;
}
declare module 'ol/MapBrowserEventType.js' {
  declare module.exports: $Exports<'ol/MapBrowserEventType'>;
}
declare module 'ol/MapBrowserPointerEvent.js' {
  declare module.exports: $Exports<'ol/MapBrowserPointerEvent'>;
}
declare module 'ol/MapEvent.js' {
  declare module.exports: $Exports<'ol/MapEvent'>;
}
declare module 'ol/MapEventType.js' {
  declare module.exports: $Exports<'ol/MapEventType'>;
}
declare module 'ol/MapProperty.js' {
  declare module.exports: $Exports<'ol/MapProperty'>;
}
declare module 'ol/math.js' {
  declare module.exports: $Exports<'ol/math'>;
}
declare module 'ol/net.js' {
  declare module.exports: $Exports<'ol/net'>;
}
declare module 'ol/obj.js' {
  declare module.exports: $Exports<'ol/obj'>;
}
declare module 'ol/Object.js' {
  declare module.exports: $Exports<'ol/Object'>;
}
declare module 'ol/ObjectEventType.js' {
  declare module.exports: $Exports<'ol/ObjectEventType'>;
}
declare module 'ol/Observable.js' {
  declare module.exports: $Exports<'ol/Observable'>;
}
declare module 'ol/Overlay.js' {
  declare module.exports: $Exports<'ol/Overlay'>;
}
declare module 'ol/OverlayPositioning.js' {
  declare module.exports: $Exports<'ol/OverlayPositioning'>;
}
declare module 'ol/pixel.js' {
  declare module.exports: $Exports<'ol/pixel'>;
}
declare module 'ol/PluggableMap.js' {
  declare module.exports: $Exports<'ol/PluggableMap'>;
}
declare module 'ol/pointer/EventSource.js' {
  declare module.exports: $Exports<'ol/pointer/EventSource'>;
}
declare module 'ol/pointer/EventType.js' {
  declare module.exports: $Exports<'ol/pointer/EventType'>;
}
declare module 'ol/pointer/MouseSource.js' {
  declare module.exports: $Exports<'ol/pointer/MouseSource'>;
}
declare module 'ol/pointer/MsSource.js' {
  declare module.exports: $Exports<'ol/pointer/MsSource'>;
}
declare module 'ol/pointer/NativeSource.js' {
  declare module.exports: $Exports<'ol/pointer/NativeSource'>;
}
declare module 'ol/pointer/PointerEvent.js' {
  declare module.exports: $Exports<'ol/pointer/PointerEvent'>;
}
declare module 'ol/pointer/PointerEventHandler.js' {
  declare module.exports: $Exports<'ol/pointer/PointerEventHandler'>;
}
declare module 'ol/pointer/TouchSource.js' {
  declare module.exports: $Exports<'ol/pointer/TouchSource'>;
}
declare module 'ol/proj.js' {
  declare module.exports: $Exports<'ol/proj'>;
}
declare module 'ol/proj/epsg3857.js' {
  declare module.exports: $Exports<'ol/proj/epsg3857'>;
}
declare module 'ol/proj/epsg4326.js' {
  declare module.exports: $Exports<'ol/proj/epsg4326'>;
}
declare module 'ol/proj/proj4.js' {
  declare module.exports: $Exports<'ol/proj/proj4'>;
}
declare module 'ol/proj/Projection.js' {
  declare module.exports: $Exports<'ol/proj/Projection'>;
}
declare module 'ol/proj/projections.js' {
  declare module.exports: $Exports<'ol/proj/projections'>;
}
declare module 'ol/proj/transforms.js' {
  declare module.exports: $Exports<'ol/proj/transforms'>;
}
declare module 'ol/proj/Units.js' {
  declare module.exports: $Exports<'ol/proj/Units'>;
}
declare module 'ol/render.js' {
  declare module.exports: $Exports<'ol/render'>;
}
declare module 'ol/render/Box.js' {
  declare module.exports: $Exports<'ol/render/Box'>;
}
declare module 'ol/render/canvas.js' {
  declare module.exports: $Exports<'ol/render/canvas'>;
}
declare module 'ol/render/canvas/ImageReplay.js' {
  declare module.exports: $Exports<'ol/render/canvas/ImageReplay'>;
}
declare module 'ol/render/canvas/Immediate.js' {
  declare module.exports: $Exports<'ol/render/canvas/Immediate'>;
}
declare module 'ol/render/canvas/Instruction.js' {
  declare module.exports: $Exports<'ol/render/canvas/Instruction'>;
}
declare module 'ol/render/canvas/LineStringReplay.js' {
  declare module.exports: $Exports<'ol/render/canvas/LineStringReplay'>;
}
declare module 'ol/render/canvas/PolygonReplay.js' {
  declare module.exports: $Exports<'ol/render/canvas/PolygonReplay'>;
}
declare module 'ol/render/canvas/Replay.js' {
  declare module.exports: $Exports<'ol/render/canvas/Replay'>;
}
declare module 'ol/render/canvas/ReplayGroup.js' {
  declare module.exports: $Exports<'ol/render/canvas/ReplayGroup'>;
}
declare module 'ol/render/canvas/TextReplay.js' {
  declare module.exports: $Exports<'ol/render/canvas/TextReplay'>;
}
declare module 'ol/render/Event.js' {
  declare module.exports: $Exports<'ol/render/Event'>;
}
declare module 'ol/render/EventType.js' {
  declare module.exports: $Exports<'ol/render/EventType'>;
}
declare module 'ol/render/Feature.js' {
  declare module.exports: $Exports<'ol/render/Feature'>;
}
declare module 'ol/render/replay.js' {
  declare module.exports: $Exports<'ol/render/replay'>;
}
declare module 'ol/render/ReplayGroup.js' {
  declare module.exports: $Exports<'ol/render/ReplayGroup'>;
}
declare module 'ol/render/ReplayType.js' {
  declare module.exports: $Exports<'ol/render/ReplayType'>;
}
declare module 'ol/render/VectorContext.js' {
  declare module.exports: $Exports<'ol/render/VectorContext'>;
}
declare module 'ol/render/webgl.js' {
  declare module.exports: $Exports<'ol/render/webgl'>;
}
declare module 'ol/render/webgl/CircleReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/CircleReplay'>;
}
declare module 'ol/render/webgl/circlereplay/defaultshader.js' {
  declare module.exports: $Exports<'ol/render/webgl/circlereplay/defaultshader'>;
}
declare module 'ol/render/webgl/circlereplay/defaultshader/Locations.js' {
  declare module.exports: $Exports<'ol/render/webgl/circlereplay/defaultshader/Locations'>;
}
declare module 'ol/render/webgl/ImageReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/ImageReplay'>;
}
declare module 'ol/render/webgl/Immediate.js' {
  declare module.exports: $Exports<'ol/render/webgl/Immediate'>;
}
declare module 'ol/render/webgl/LineStringReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/LineStringReplay'>;
}
declare module 'ol/render/webgl/linestringreplay/defaultshader.js' {
  declare module.exports: $Exports<'ol/render/webgl/linestringreplay/defaultshader'>;
}
declare module 'ol/render/webgl/linestringreplay/defaultshader/Locations.js' {
  declare module.exports: $Exports<'ol/render/webgl/linestringreplay/defaultshader/Locations'>;
}
declare module 'ol/render/webgl/PolygonReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/PolygonReplay'>;
}
declare module 'ol/render/webgl/polygonreplay/defaultshader.js' {
  declare module.exports: $Exports<'ol/render/webgl/polygonreplay/defaultshader'>;
}
declare module 'ol/render/webgl/polygonreplay/defaultshader/Locations.js' {
  declare module.exports: $Exports<'ol/render/webgl/polygonreplay/defaultshader/Locations'>;
}
declare module 'ol/render/webgl/Replay.js' {
  declare module.exports: $Exports<'ol/render/webgl/Replay'>;
}
declare module 'ol/render/webgl/ReplayGroup.js' {
  declare module.exports: $Exports<'ol/render/webgl/ReplayGroup'>;
}
declare module 'ol/render/webgl/TextReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/TextReplay'>;
}
declare module 'ol/render/webgl/TextureReplay.js' {
  declare module.exports: $Exports<'ol/render/webgl/TextureReplay'>;
}
declare module 'ol/render/webgl/texturereplay/defaultshader.js' {
  declare module.exports: $Exports<'ol/render/webgl/texturereplay/defaultshader'>;
}
declare module 'ol/render/webgl/texturereplay/defaultshader/Locations.js' {
  declare module.exports: $Exports<'ol/render/webgl/texturereplay/defaultshader/Locations'>;
}
declare module 'ol/renderer/canvas/ImageLayer.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/ImageLayer'>;
}
declare module 'ol/renderer/canvas/IntermediateCanvas.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/IntermediateCanvas'>;
}
declare module 'ol/renderer/canvas/Layer.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/Layer'>;
}
declare module 'ol/renderer/canvas/Map.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/Map'>;
}
declare module 'ol/renderer/canvas/TileLayer.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/TileLayer'>;
}
declare module 'ol/renderer/canvas/VectorLayer.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/VectorLayer'>;
}
declare module 'ol/renderer/canvas/VectorTileLayer.js' {
  declare module.exports: $Exports<'ol/renderer/canvas/VectorTileLayer'>;
}
declare module 'ol/renderer/Layer.js' {
  declare module.exports: $Exports<'ol/renderer/Layer'>;
}
declare module 'ol/renderer/Map.js' {
  declare module.exports: $Exports<'ol/renderer/Map'>;
}
declare module 'ol/renderer/vector.js' {
  declare module.exports: $Exports<'ol/renderer/vector'>;
}
declare module 'ol/renderer/webgl/defaultmapshader.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/defaultmapshader'>;
}
declare module 'ol/renderer/webgl/defaultmapshader/Locations.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/defaultmapshader/Locations'>;
}
declare module 'ol/renderer/webgl/ImageLayer.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/ImageLayer'>;
}
declare module 'ol/renderer/webgl/Layer.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/Layer'>;
}
declare module 'ol/renderer/webgl/Map.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/Map'>;
}
declare module 'ol/renderer/webgl/TileLayer.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/TileLayer'>;
}
declare module 'ol/renderer/webgl/tilelayershader.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/tilelayershader'>;
}
declare module 'ol/renderer/webgl/tilelayershader/Locations.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/tilelayershader/Locations'>;
}
declare module 'ol/renderer/webgl/VectorLayer.js' {
  declare module.exports: $Exports<'ol/renderer/webgl/VectorLayer'>;
}
declare module 'ol/reproj.js' {
  declare module.exports: $Exports<'ol/reproj'>;
}
declare module 'ol/reproj/common.js' {
  declare module.exports: $Exports<'ol/reproj/common'>;
}
declare module 'ol/reproj/Image.js' {
  declare module.exports: $Exports<'ol/reproj/Image'>;
}
declare module 'ol/reproj/Tile.js' {
  declare module.exports: $Exports<'ol/reproj/Tile'>;
}
declare module 'ol/reproj/Triangulation.js' {
  declare module.exports: $Exports<'ol/reproj/Triangulation'>;
}
declare module 'ol/resolutionconstraint.js' {
  declare module.exports: $Exports<'ol/resolutionconstraint'>;
}
declare module 'ol/rotationconstraint.js' {
  declare module.exports: $Exports<'ol/rotationconstraint'>;
}
declare module 'ol/size.js' {
  declare module.exports: $Exports<'ol/size'>;
}
declare module 'ol/source.js' {
  declare module.exports: $Exports<'ol/source'>;
}
declare module 'ol/source/BingMaps.js' {
  declare module.exports: $Exports<'ol/source/BingMaps'>;
}
declare module 'ol/source/CartoDB.js' {
  declare module.exports: $Exports<'ol/source/CartoDB'>;
}
declare module 'ol/source/Cluster.js' {
  declare module.exports: $Exports<'ol/source/Cluster'>;
}
declare module 'ol/source/common.js' {
  declare module.exports: $Exports<'ol/source/common'>;
}
declare module 'ol/source/Image.js' {
  declare module.exports: $Exports<'ol/source/Image'>;
}
declare module 'ol/source/ImageArcGISRest.js' {
  declare module.exports: $Exports<'ol/source/ImageArcGISRest'>;
}
declare module 'ol/source/ImageCanvas.js' {
  declare module.exports: $Exports<'ol/source/ImageCanvas'>;
}
declare module 'ol/source/ImageMapGuide.js' {
  declare module.exports: $Exports<'ol/source/ImageMapGuide'>;
}
declare module 'ol/source/ImageStatic.js' {
  declare module.exports: $Exports<'ol/source/ImageStatic'>;
}
declare module 'ol/source/ImageWMS.js' {
  declare module.exports: $Exports<'ol/source/ImageWMS'>;
}
declare module 'ol/source/OSM.js' {
  declare module.exports: $Exports<'ol/source/OSM'>;
}
declare module 'ol/source/Raster.js' {
  declare module.exports: $Exports<'ol/source/Raster'>;
}
declare module 'ol/source/Source.js' {
  declare module.exports: $Exports<'ol/source/Source'>;
}
declare module 'ol/source/Stamen.js' {
  declare module.exports: $Exports<'ol/source/Stamen'>;
}
declare module 'ol/source/State.js' {
  declare module.exports: $Exports<'ol/source/State'>;
}
declare module 'ol/source/Tile.js' {
  declare module.exports: $Exports<'ol/source/Tile'>;
}
declare module 'ol/source/TileArcGISRest.js' {
  declare module.exports: $Exports<'ol/source/TileArcGISRest'>;
}
declare module 'ol/source/TileDebug.js' {
  declare module.exports: $Exports<'ol/source/TileDebug'>;
}
declare module 'ol/source/TileEventType.js' {
  declare module.exports: $Exports<'ol/source/TileEventType'>;
}
declare module 'ol/source/TileImage.js' {
  declare module.exports: $Exports<'ol/source/TileImage'>;
}
declare module 'ol/source/TileJSON.js' {
  declare module.exports: $Exports<'ol/source/TileJSON'>;
}
declare module 'ol/source/TileWMS.js' {
  declare module.exports: $Exports<'ol/source/TileWMS'>;
}
declare module 'ol/source/UrlTile.js' {
  declare module.exports: $Exports<'ol/source/UrlTile'>;
}
declare module 'ol/source/UTFGrid.js' {
  declare module.exports: $Exports<'ol/source/UTFGrid'>;
}
declare module 'ol/source/Vector.js' {
  declare module.exports: $Exports<'ol/source/Vector'>;
}
declare module 'ol/source/VectorEventType.js' {
  declare module.exports: $Exports<'ol/source/VectorEventType'>;
}
declare module 'ol/source/VectorTile.js' {
  declare module.exports: $Exports<'ol/source/VectorTile'>;
}
declare module 'ol/source/WMSServerType.js' {
  declare module.exports: $Exports<'ol/source/WMSServerType'>;
}
declare module 'ol/source/WMTS.js' {
  declare module.exports: $Exports<'ol/source/WMTS'>;
}
declare module 'ol/source/WMTSRequestEncoding.js' {
  declare module.exports: $Exports<'ol/source/WMTSRequestEncoding'>;
}
declare module 'ol/source/XYZ.js' {
  declare module.exports: $Exports<'ol/source/XYZ'>;
}
declare module 'ol/source/Zoomify.js' {
  declare module.exports: $Exports<'ol/source/Zoomify'>;
}
declare module 'ol/sphere.js' {
  declare module.exports: $Exports<'ol/sphere'>;
}
declare module 'ol/string.js' {
  declare module.exports: $Exports<'ol/string'>;
}
declare module 'ol/structs/LinkedList.js' {
  declare module.exports: $Exports<'ol/structs/LinkedList'>;
}
declare module 'ol/structs/LRUCache.js' {
  declare module.exports: $Exports<'ol/structs/LRUCache'>;
}
declare module 'ol/structs/PriorityQueue.js' {
  declare module.exports: $Exports<'ol/structs/PriorityQueue'>;
}
declare module 'ol/structs/RBush.js' {
  declare module.exports: $Exports<'ol/structs/RBush'>;
}
declare module 'ol/style.js' {
  declare module.exports: $Exports<'ol/style'>;
}
declare module 'ol/style/Atlas.js' {
  declare module.exports: $Exports<'ol/style/Atlas'>;
}
declare module 'ol/style/AtlasManager.js' {
  declare module.exports: $Exports<'ol/style/AtlasManager'>;
}
declare module 'ol/style/Circle.js' {
  declare module.exports: $Exports<'ol/style/Circle'>;
}
declare module 'ol/style/Fill.js' {
  declare module.exports: $Exports<'ol/style/Fill'>;
}
declare module 'ol/style/Icon.js' {
  declare module.exports: $Exports<'ol/style/Icon'>;
}
declare module 'ol/style/IconAnchorUnits.js' {
  declare module.exports: $Exports<'ol/style/IconAnchorUnits'>;
}
declare module 'ol/style/IconImage.js' {
  declare module.exports: $Exports<'ol/style/IconImage'>;
}
declare module 'ol/style/IconImageCache.js' {
  declare module.exports: $Exports<'ol/style/IconImageCache'>;
}
declare module 'ol/style/IconOrigin.js' {
  declare module.exports: $Exports<'ol/style/IconOrigin'>;
}
declare module 'ol/style/Image.js' {
  declare module.exports: $Exports<'ol/style/Image'>;
}
declare module 'ol/style/RegularShape.js' {
  declare module.exports: $Exports<'ol/style/RegularShape'>;
}
declare module 'ol/style/Stroke.js' {
  declare module.exports: $Exports<'ol/style/Stroke'>;
}
declare module 'ol/style/Style.js' {
  declare module.exports: $Exports<'ol/style/Style'>;
}
declare module 'ol/style/Text.js' {
  declare module.exports: $Exports<'ol/style/Text'>;
}
declare module 'ol/style/TextPlacement.js' {
  declare module.exports: $Exports<'ol/style/TextPlacement'>;
}
declare module 'ol/Tile.js' {
  declare module.exports: $Exports<'ol/Tile'>;
}
declare module 'ol/TileCache.js' {
  declare module.exports: $Exports<'ol/TileCache'>;
}
declare module 'ol/tilecoord.js' {
  declare module.exports: $Exports<'ol/tilecoord'>;
}
declare module 'ol/tilegrid.js' {
  declare module.exports: $Exports<'ol/tilegrid'>;
}
declare module 'ol/tilegrid/common.js' {
  declare module.exports: $Exports<'ol/tilegrid/common'>;
}
declare module 'ol/tilegrid/TileGrid.js' {
  declare module.exports: $Exports<'ol/tilegrid/TileGrid'>;
}
declare module 'ol/tilegrid/WMTS.js' {
  declare module.exports: $Exports<'ol/tilegrid/WMTS'>;
}
declare module 'ol/TileQueue.js' {
  declare module.exports: $Exports<'ol/TileQueue'>;
}
declare module 'ol/TileRange.js' {
  declare module.exports: $Exports<'ol/TileRange'>;
}
declare module 'ol/TileState.js' {
  declare module.exports: $Exports<'ol/TileState'>;
}
declare module 'ol/tileurlfunction.js' {
  declare module.exports: $Exports<'ol/tileurlfunction'>;
}
declare module 'ol/transform.js' {
  declare module.exports: $Exports<'ol/transform'>;
}
declare module 'ol/uri.js' {
  declare module.exports: $Exports<'ol/uri'>;
}
declare module 'ol/util.js' {
  declare module.exports: $Exports<'ol/util'>;
}
declare module 'ol/vec/mat4.js' {
  declare module.exports: $Exports<'ol/vec/mat4'>;
}
declare module 'ol/VectorImageTile.js' {
  declare module.exports: $Exports<'ol/VectorImageTile'>;
}
declare module 'ol/VectorTile.js' {
  declare module.exports: $Exports<'ol/VectorTile'>;
}
declare module 'ol/View.js' {
  declare module.exports: $Exports<'ol/View'>;
}
declare module 'ol/ViewHint.js' {
  declare module.exports: $Exports<'ol/ViewHint'>;
}
declare module 'ol/ViewProperty.js' {
  declare module.exports: $Exports<'ol/ViewProperty'>;
}
declare module 'ol/webgl.js' {
  declare module.exports: $Exports<'ol/webgl'>;
}
declare module 'ol/webgl/Buffer.js' {
  declare module.exports: $Exports<'ol/webgl/Buffer'>;
}
declare module 'ol/webgl/Context.js' {
  declare module.exports: $Exports<'ol/webgl/Context'>;
}
declare module 'ol/webgl/ContextEventType.js' {
  declare module.exports: $Exports<'ol/webgl/ContextEventType'>;
}
declare module 'ol/webgl/Fragment.js' {
  declare module.exports: $Exports<'ol/webgl/Fragment'>;
}
declare module 'ol/webgl/Shader.js' {
  declare module.exports: $Exports<'ol/webgl/Shader'>;
}
declare module 'ol/webgl/Vertex.js' {
  declare module.exports: $Exports<'ol/webgl/Vertex'>;
}
declare module 'ol/WebGLMap.js' {
  declare module.exports: $Exports<'ol/WebGLMap'>;
}
declare module 'ol/xml.js' {
  declare module.exports: $Exports<'ol/xml'>;
}
